import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/Layouts/MainLayout";
import CustomReduxProvider from "@/redux/CustomReduxProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> 
        <CustomReduxProvider  >
          <MainLayout>
            {children}
          </MainLayout>
        </CustomReduxProvider>
      </body>
    </html>
  );
}